---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  - git config --global push.followTags true
  - npm config set spin false

script:
  - npm test

after_success:
  - ./scripts/release.sh
