---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

notifications:
  email: false

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  - git config --global push.followTags true
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn test

after_success:
  - ./scripts/release.sh
