---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false

script:
  - npm test

after_success:
  - ./scripts/release.sh
